const data = [
{
    id:6,
    img:"/images/blog/6.jpg",
    alt:"blog1",
    date:"August 15, 2020 2 Comments",
    title:"Lorem ipsum dolor sit amet, consetetur",
    desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut.",
},
{
    id:3,
    img:"/images/blog/3.jpg",
    alt:"blog1",
    date:"August 15, 2020 2 Comments",
    title:"Lorem ipsum dolor sit amet, consetetur",
    desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut.",
},
{
    id:7,
    img:"/images/blog/7.jpg",
    alt:"blog1",
    date:"August 15, 2020 2 Comments",
    title:"Lorem ipsum dolor sit amet, consetetur",
    desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut.",
},
{
    id:6,
    img:"/images/blog/6.jpg",
    alt:"blog1",
    date:"August 15, 2020 2 Comments",
    title:"Lorem ipsum dolor sit amet, consetetur",
    desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut.",
},
{
    id:3,
    img:"/images/blog/3.jpg",
    alt:"blog1",
    date:"August 15, 2020 2 Comments",
    title:"Lorem ipsum dolor sit amet, consetetur",
    desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut.",
},
{
    id:7,
    img:"/images/blog/7.jpg",
    alt:"blog1",
    date:"August 15, 2020 2 Comments",
    title:"Lorem ipsum dolor sit amet, consetetur",
    desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut.",
},{
    id:6,
    img:"/images/blog/6.jpg",
    alt:"blog1",
    date:"August 15, 2020 2 Comments",
    title:"Lorem ipsum dolor sit amet, consetetur",
    desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut.",
},
{
    id:3,
    img:"/images/blog/3.jpg",
    alt:"blog1",
    date:"August 15, 2020 2 Comments",
    title:"Lorem ipsum dolor sit amet, consetetur",
    desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut.",
},
{
    id:7,
    img:"/images/blog/7.jpg",
    alt:"blog1",
    date:"August 15, 2020 2 Comments",
    title:"Lorem ipsum dolor sit amet, consetetur",
    desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut.",
}
]

export default data;